export const countryOptions = [
  { code: 'AU', name: 'Australia', phoneCode: '+61' },
  { code: 'BR', name: 'Brazil', phoneCode: '+55' },
  { code: 'CN', name: 'China', phoneCode: '+86' },
  { code: 'FR', name: 'France', phoneCode: '+33' },
  { code: 'DE', name: 'Germany', phoneCode: '+49' },
  { code: 'IN', name: 'India', phoneCode: '+91' },
  { code: 'IE', name: 'Ireland', phoneCode: '+353' },
  { code: 'IT', name: 'Italy', phoneCode: '+39' },
  { code: 'JP', name: 'Japan', phoneCode: '+81' },
  { code: 'MX', name: 'Mexico', phoneCode: '+52' },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31' },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64' },
  { code: 'NO', name: 'Norway', phoneCode: '+47' },
  { code: 'PL', name: 'Poland', phoneCode: '+48' },
  { code: 'RU', name: 'Russia', phoneCode: '+7' },
  { code: 'SG', name: 'Singapore', phoneCode: '+65' },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27' },
  { code: 'KR', name: 'South Korea', phoneCode: '+82' },
  { code: 'ES', name: 'Spain', phoneCode: '+34' },
  { code: 'SE', name: 'Sweden', phoneCode: '+46' },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41' },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971' },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44' },
  { code: 'US', name: 'United States', phoneCode: '+1' },
];
